/**
 * Build step: inline webapp/dist/* (the v0.4 React/Vite bundle) into
 * src/ui/webapp.ts as a single exported HTML string. Keeps the CLI's
 * single-file distribution invariant (skill-manager-cli ships one
 * `dist/` tree, no separate static asset directory).
 *
 * Pipeline:
 *   1. Assume `pnpm --filter @skill-manager/webapp build` has already
 *      produced webapp/dist/{index.html, assets/*.css, assets/*.js}.
 *      The root `pnpm build` script chains them so this is always
 *      true in practice.
 *   2. Read webapp/dist/index.html.
 *   3. For each <link rel="stylesheet" href="/assets/X.css">, replace
 *      with <style>…inlined…</style>.
 *   4. For each <script type="module" src="/assets/X.js">, replace
 *      with <script type="module">…inlined…</script>.
 *   5. Wrap the result in a TS template literal.
 *
 * No regex-driven HTML parsing beyond what's necessary: we only touch
 * the asset references Vite emits, which follow a very stable shape.
 */
import { readFile, writeFile } from "node:fs/promises";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");
const DIST = resolve(ROOT, "webapp/dist");
const OUT = resolve(ROOT, "src/ui/webapp.ts");

function escapeForTemplateLiteral(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
}

async function readDistAsset(href: string): Promise<string> {
  // href looks like "/assets/index-XXXX.css" — strip the leading slash.
  const rel = href.replace(/^\//, "");
  return readFile(resolve(DIST, rel), "utf8");
}

async function inlineStylesheets(html: string): Promise<string> {
  const linkRe = /<link\s+rel="stylesheet"[^>]*?href="([^"]+)"[^>]*?>/g;
  const replacements: Array<{ match: string; replacement: string }> = [];
  let m: RegExpExecArray | null;
  while ((m = linkRe.exec(html))) {
    const href = m[1];
    const css = await readDistAsset(href);
    replacements.push({
      match: m[0],
      replacement: `<style>${css.trimEnd()}</style>`,
    });
  }
  let out = html;
  for (const r of replacements) {
    out = out.replace(r.match, () => r.replacement);
  }
  return out;
}

async function inlineModuleScripts(html: string): Promise<string> {
  const scriptRe = /<script\s+type="module"[^>]*?src="([^"]+)"[^>]*?><\/script>/g;
  const replacements: Array<{ match: string; replacement: string }> = [];
  let m: RegExpExecArray | null;
  while ((m = scriptRe.exec(html))) {
    const src = m[1];
    const js = await readDistAsset(src);
    replacements.push({
      match: m[0],
      replacement: `<script type="module">${js.trimEnd()}</script>`,
    });
  }
  let out = html;
  for (const r of replacements) {
    out = out.replace(r.match, () => r.replacement);
  }
  return out;
}

async function main(): Promise<void> {
  const html = await readFile(resolve(DIST, "index.html"), "utf8");
  let inlined = await inlineStylesheets(html);
  inlined = await inlineModuleScripts(inlined);

  const banner =
    `// AUTO-GENERATED by scripts/build-web.ts. Do not edit by hand.\n` +
    `// Source files live under webapp/ (built by Vite into webapp/dist/).\n`;

  const ts = `${banner}export const WEBAPP_HTML = \`${escapeForTemplateLiteral(inlined)}\`;\n`;

  await writeFile(OUT, ts, "utf8");
  process.stdout.write(
    `[build-web] wrote ${OUT} (${ts.length} chars; html in=${html.length}, html out=${inlined.length})\n`,
  );
}

main().catch((err) => {
  process.stderr.write(
    `[build-web] failed: ${err instanceof Error ? (err.stack ?? err.message) : String(err)}\n`,
  );
  process.exitCode = 1;
});
