/**
 * Build script: inline src/ui/web/{index.html,styles.css,app.js,vendor/petite-vue.iife.js}
 * into src/ui/webapp.ts as a single exported template string.
 *
 * Run: pnpm tsx scripts/build-web.ts
 * Auto-invoked before tsc via the "build" script in package.json.
 */
import { readFile, writeFile } from "node:fs/promises";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");
const WEB = resolve(ROOT, "src/ui/web");
const OUT = resolve(ROOT, "src/ui/webapp.ts");

function escapeForTemplateLiteral(s: string): string {
  // Escape backslashes first, then backticks, then ${ interpolation starts.
  return s.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
}

async function readText(rel: string): Promise<string> {
  return readFile(resolve(WEB, rel), "utf8");
}

async function main(): Promise<void> {
  const [html, css, app, vendor] = await Promise.all([
    readText("index.html"),
    readText("styles.css"),
    readText("app.js"),
    readText("vendor/petite-vue.iife.js"),
  ]);

  // Inject petite-vue vendor + app code into a single <script> block.
  // Using a vendor IIFE that exposes window.PetiteVue.
  const scriptBundle = `// vendor: petite-vue 0.4.1 (MIT)\n${vendor}\n// app:\n${app}`;

  const filled = html
    .replace("/* __STYLES__ */", () => css.trimEnd())
    .replace("/* __APP__ */", () => scriptBundle.trimEnd());

  const banner =
    `// AUTO-GENERATED by scripts/build-web.ts. Do not edit by hand.\n` +
    `// Source files live under src/ui/web/.\n`;

  const ts = `${banner}export const WEBAPP_HTML = \`${escapeForTemplateLiteral(filled)}\`;\n`;

  await writeFile(OUT, ts, "utf8");
  process.stdout.write(
    `[build-web] wrote ${OUT} (${ts.length} chars; html=${html.length}, css=${css.length}, app=${app.length}, vendor=${vendor.length})\n`,
  );
}

main().catch((err) => {
  process.stderr.write(`[build-web] failed: ${err instanceof Error ? err.stack ?? err.message : String(err)}\n`);
  process.exitCode = 1;
});
